### PR TITLE
Update getting smart collection products to use correct endpoint

### PR DESCRIPTION
**Pull request by lizkenyon**
* As of 2020-04 to get the the products in a smart collection you must use the collections resource
* https://shopify.dev/docs/admin-api/rest/reference/products/smartcollection?api[version]=2020-04
* https://shopify.dev/docs/admin-api/rest/reference/products/collect?api[version]=2020-04#index-2020-04

### CODE REVIEW

**Comment by theRTC204** [comment]
Does this change break compatibility for anyone who may still be using API versions older than 2020-04?

**Comment by lizkenyon** [comment]
So this will not work for any api version older than 2020-04.

But it seems that `/smart_collections/id/products` has never worked. (I can't find anything in the docs for even the older versions, and I am getting a 404)

The old way to get the products in the collection is to use the `/collect`, so anyone using an older API version should be using a different method.

**Comment by theRTC204** [comment]
This presents and interesting quandary... do we treat this change as a patch or a major change?

I just tested the existing endpoint going back to API version 2019-04 (the oldest currently selectable API version) and can confirm it does not seem to exist at all anymore. I would imagine it existed at some point, otherwise we wouldn't have referenced it - but perhaps it's been completely decommissioned.

I suppose since the library is currently broken regardless of which API version a consumer is targeting, we can probably safely treat this as a patch. Anyone else have thoughts on that?

As an aside, we should consider updating this library to allow specifying a target API version.

**Comment by dgetson** [comment]
It appears that the `/smart_collections/id/products` was supposed to replace the `collects` in the Recurring Orders Enterprise/Product Shuffle app. But no shops ended up using the Feature flag that used that endpoint so I don't think it ever got run. So it might not have ever existed.

**Comment by Wryte** [comment]
@theRTC204 

> This presents and interesting quandary... do we treat this change as a patch or a major change?
> 
> I just tested the existing endpoint going back to API version 2019-04 (the oldest currently selectable API version) and can confirm it does not seem to exist at all anymore. I would imagine it existed at some point, otherwise we wouldn't have referenced it - but perhaps it's been completely decommissioned.
> 
> I suppose since the library is currently broken regardless of which API version a consumer is targeting, we can probably safely treat this as a patch. Anyone else have thoughts on that?

I think that releasing this as a patch makes sense to me. If the endpoint is completely non existent no one can be using it to begin with.

> As an aside, we should consider updating this library to allow specifying a target API version.

I think we already did that IIRC. It was one of the first changes when the enforced API version updates hammer started to fall.

**Comment by theRTC204** [comment]
> I think we already did that IIRC. It was one of the first changes when the enforced API version updates hammer started to fall.

Well, aren't we on top of things! (except for me, who's apparently out of touch!)

**Pull request merged**
