### PR TITLE
Php 8 upgrade

### PR DESCRIPTION
**Pull request by kfalkowski11**
Expanding on previous MR: https://github.com/bold-commerce/bold-shopify-toolkit/pull/135 

Updated Dockerfile to use PHP 8.1.9
Updated composer.json file to use package version:
* PHP Unit 8.5.*
* PHP CS Fixer 2.18.*
* Guzzlehttp/guzzle 7.1.*

Updated tests cases to be compatible

### CODE REVIEW

**Review by Wryte — CHANGES_REQUESTED** [review]
Looks like we are going to need to update some things in the `.circleci` folder as well.

I think we need to change the build docker image to 8.X

```yml
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:5.6.37-apache-jessie
```

and then upgrade our composer version to 2.X

```yml
      - run:
          name: Install Composer
          command: |
// ...
            php composer-setup.php --version=1.10.16
// ...
```

The current pipeline for this PR failed because it was out of memory but we will try this first and it could help.

**Review by Wryte — CHANGES_REQUESTED** [review]
Looks like you're going to need to upgrade CS fixer further so that it supports PHP 8.1. Looking at the latest version it does support it.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/composer.json#L17

Not sure why circleci isn't linking the pipelines in here but here is the failing pipeline

https://app.circleci.com/pipelines/github/bold-commerce/bold-shopify-toolkit/161/workflows/56be37f1-4684-4367-b81c-252e39268a4a/jobs/408

**Comment by Wryte** [comment]
Here's a link to the pipelines for this PR

https://app.circleci.com/pipelines/github/bold-commerce/bold-shopify-toolkit?branch=pull%2F152

**Comment by kfalkowski11** [comment]
Fixed up the .circleci folder as well as the cs fixer version, pipeline is passing now.

There are a number of cs fixer changes now in this MR to follow the updated PSR2 and Symfony rules.

**Review by Wryte — APPROVED** [review]

**Pull request merged**
