### PR TITLE
Handle RequestException without a response

### PR DESCRIPTION
**Pull request by nathankoop**
This time with less merge conflicts

### CODE REVIEW

**Comment by nathankoop** [comment]
@theRTC204 Updated this MR.

Note the Services/Client no longer requires a change. It was changed in December.

**Comment by theRTC204** [comment]
Thinking on this more, if we're doing this change here we should probably apply this change to all services that also attempt to access the response object.

**Comment by nathankoop** [comment]
Yeah I handled all the RequestException.

I'll create another PR (or update this one) later tonight or tomorrow.

**Comment by nathankoop** [comment]
These appear to be the only three instances of the response being used.

/Services/Asset
/Services/InstallAndLogin
/Services/Client


All three are handled now.

**Pull request merged**
