### PR TITLE
Fixed Multiple Variant Services

### PR DESCRIPTION
**Pull request by James300**
I noticed that a few of the Variant services had the wrong paths or that the parameters being passed in where being used incorrectly, so here's the fix.

P.S. I only fixed one's that were broken meaning people couldn't have been using them, so no fear of breaking a bunch of stuff.

### CODE REVIEW

**Comment by jerairrest** [comment]
And these changes work?

**Comment by James300** [comment]
@jerairrest Yes, tested and working locally.

**Comment by rickywiens** [comment]
I think you can update metafields in both of these ways. Are you sure that they are broken? The Shopify documentation specifically refers to metafields in the original way this function worked:

https://help.shopify.com/api/reference/metafield


The way you changed it to Shopify considers "Shop" Metafields, though I don't doubt both methods work.

**Comment by James300** [comment]
@rickywiens The update was broken because of `$raw = $this->client->post("admin/variants/{$product->getId()}/metafields/{$variant->getId()}.json", [], $serializedModel);` specifically product id being used where variant id should and variant id where metafield id should.

**Comment by rickywiens** [comment]
I am ok with this now

**Pull request merged**
