### PR TITLE
Fixing login from Shopify

### PR DESCRIPTION
**Pull request by CoryMik**
Shopify recently added session as a get parameters when logging in from the the app page of the Shopify admin section. So with the old code anything not hardcoded in the if statement would be excluded from the hmac verification and according to shopify we should only be removing the hmac from the request and nothing else. So the hmac and the signature were not the same. Instead of just adding session I think we should just skip the hmac parameter which will allow shopify to add any parameters in the future. 

Here's the link to shopify's api documentation mentioned.
https://help.shopify.com/en/api/getting-started/authentication/oauth#verification

### CODE REVIEW

**Comment by tysonkroeker** [comment]
Can confirm, the above will work.  They have also not yet updated their documentation with the session variable.

**Comment by theRTC204** [comment]
Does this change risk creating an issue with the opposite effect of including values in the HMAC that should not be included? Does Shopify have any additional documentation on which query params are always sent?

**Comment by tysonkroeker** [comment]
Shopify's docs say to only remove the hmac param.  Because we had a whitelist of params we allowed through instead of a blacklist of which params to ignore (only hmac) anytime they add a param we would have broken.  The way Cory set it up should be more resilient.

**Comment by theRTC204** [comment]
I am fine with the risk, however the code will need to be adjusted to make the tests pass.

**Comment by CoryMik** [comment]
updated the syntax

**Comment by tysonkroeker** [comment]
Do we need anyone else to review this before we can merge it?  This is blocking some major work for me.

**Pull request merged**
